# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Memcached
version:      1.18
version_from: lib/Cache/Memcached.pm
installdirs:  site
requires:
    Storable:                      0
    String::CRC32:                 0
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
